random_seed: 42

dataset:

  source: sklearn

  name: breast_cancer

  path: null

  target_column: target

# if user uploads a csv dataset. 
#dataset:

  #source: csv

  #path: data/heart.csv

  #target_column: diagnosis

# if user uploads through streamlit directly.
#dataset:

  #source: csv

  #path: uploads/diabetes.csv

  #target_column: Outcome


cross_validation:
  folds: 5


reporting:
  save_reports: true